tournament:
  num_rounds: 10
  show_games: false
  show_end_state: false

# ===========================================

# game:
#   type: TicTacToe
#   rows: 3 # rows == cols

game:
  type: ConnectX
  rows: 6
  cols: 7
  in_a_row: 4

# ===========================================
# player_1:
#   type: random

# player_1:
#   type: human

player_1:
  type: mcts
  num_searches: 50
  C: 1.41 # Typically sqrt(2)

# player_1:
#   type: alpha_zero
#   num_searches: 10
#   C: 1.41
#   model_path: checkpoints/model_connect_four.pt
#   model_path: checkpoints/model_tic_tac_toe.pt
#   temperature: 0.0
#   exploration_steps: 0
#   dirichlet_epsilon: 0 # dirichlet is not used
#   dirichlet_alpha: 0.3 # not used
#   device: cpu

# ===========================================

# player_2:
#   type: random

# player_2:
#   type: human

# player_2:
#   type: mcts
#   num_searches: 600
#   C: 1.41

player_2:
  type: alpha_zero
  num_searches: 60
  C: 1.41
  # model_path: checkpoints/model_tic_tac_toe.pt
  model_path: checkpoints/model_connect_four.pt
  temperature: 0.0
  exploration_steps: 0
  dirichlet_epsilon: 0 # dirichlet noise is used only when training
  dirichlet_alpha: 0.3 # not used
  device: cpu